sonar.projectKey=Logiflow-Gavilanes-ECI_logiflow
sonar.projectName=LogiFlow \u2013 Logiflow
sonar.organization=logiflow-gavilanes-eci
sonar.sources=mock-server
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/docker-compose.yml,postman/**
sonar.coverage.exclusions=test/**
