sonar.projectKey=Logiflow-Gavilanes-ECI_logiflow
sonar.organization=logiflow-gavilanes-eci

sonar.projectName=logiflow-services-automation
sonar.sourceEncoding=UTF-8
sonar.sources=mock-server,openclaw,n8n
sonar.tests=test
